name: proxyapp
description: "Tu red. Tus reglas."
publish_to: 'none'
version: 1.0.2+4

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_material_symbols: ^0.0.4
  provider: ^6.1.2
  animations: ^2.0.11
  shared_preferences: ^2.0.15
  intl: ^0.20.2
  package_info_plus: ^8.0.0
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true
  generate: true
  assets:
     - assets/images/logo.png
     - assets/images/splash_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash_logo.png"
  adaptive_icon_background: "#00000000"
  adaptive_icon_foreground: "assets/images/splash_logo.png"
  remove_alpha_ios: true